apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: piggymetrics
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: notification-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: piggymetrics
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: ghcr.io/nikhildhakad55/piggymetrics-notification-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: CONFIG_SERVICE_PASSWORD
        - name: NOTIFICATION_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: NOTIFICATION_SERVICE_PASSWORD
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: MONGODB_PASSWORD
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        - name: RIBBON_EUREKA_ENABLED
          value: "false"
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
