apiVersion: v1
kind: Secret
metadata:
  name: piggymetrics-secrets
  namespace: piggymetrics
type: Opaque
data:
  CONFIG_SERVICE_PASSWORD: cGlnZ3ltZXRyaWNz # base64 for 'piggymetrics'
  NOTIFICATION_SERVICE_PASSWORD: cGlnZ3ltZXRyaWNz
  STATISTICS_SERVICE_PASSWORD: cGlnZ3ltZXRyaWNz
  ACCOUNT_SERVICE_PASSWORD: cGlnZ3ltZXRyaWNz
  MONGODB_PASSWORD: cGlnZ3ltZXRyaWNz
