apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: piggymetrics
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: piggymetrics
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ghcr.io/nikhildhakad55/piggymetrics-auth-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: CONFIG_SERVICE_PASSWORD
        - name: ACCOUNT_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: ACCOUNT_SERVICE_PASSWORD
        - name: STATISTICS_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: STATISTICS_SERVICE_PASSWORD
        - name: NOTIFICATION_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: NOTIFICATION_SERVICE_PASSWORD
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics-secrets
              key: MONGODB_PASSWORD
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        - name: RIBBON_EUREKA_ENABLED
          value: "false"
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
